apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmysql
spec:
  selector:
    matchLabels:
      app: dbmysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dbmysql
    spec:
      containers:
      - image: mysql:latest
        name: dbmysql
        envFrom:
        - configMapRef:
            name: db-config
        - secretRef: 
            name: db-secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: dbmysql-svc
  labels:
    app: dbmysql
spec:
  ports:
  - port: 3306
  selector:
    app: dbmysql
